const aboutData = [
  {
    firstName: "Sara",
    lastName: "Khan",
    team: "Medical",
    title: "TBC",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Imran",
    lastName: "Khan",
    team: "Medical",
    title: "TBC",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Matt",
    lastName: "Perez",
    team: "Medical",
    title: "TBC",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Andrea",
    lastName: "Jainarine",
    team: "Medical",
    title: "TBC",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Darwin",
    lastName: "Jean",
    team: "Medical",
    title: "TBC",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Muhammad",
    lastName: "Hamza",
    team: "Engineering",
    title: "Full Stack Software Engineer",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "https://github.com/muhamrif",
  },
  {
    firstName: "Emmanuel",
    lastName: "Cruz",
    team: "Engineering",
    title: "Full Stack Software Engineer",
    picture: "/teamPics/1.png",
    summary: "",
    linkedin: "",
    github: "https://github.com/emmanuelcruz5",
  },
  {
    firstName: "Cynthia",
    lastName: "Brito-Mena",
    team: "Engineering",
    title: "Full Stack Software Engineer",
    picture: "/teamPics/3.png",
    summary: "",
    linkedin: "https://linkedin.com/in/cynthiabritomena",
    github: "https://github.com/cb2866",
  },
  {
    firstName: "Tasnim",
    lastName: "Mollah",
    team: "Engineering",
    title: "Full Stack Software Engineer",
    picture: "/teamPics/2.png",
    summary:
      "Tasnim (she/hers) is one of MedExperts’ Founding Engineers, developing administrative features and maintaining the database and servers. She is a Fullstack Academy alum, focusing on backend engineering. Based in New York City, she enjoys trying different cuisines, good coffee, and cold weather.",
    linkedin: "",
    github: "https://github.com/Tasnimmollah",
  },
  {
    firstName: "Sarah",
    lastName: "Alli",
    team: "Engineering",
    title: "Full Stack Software Engineer",
    picture: "/teamPics/cody.png",
    summary: "",
    linkedin: "",
    github: "https://github.com/se7en-illa",
  },
];

module.exports = { aboutData };
