const aboutData = [
  {
    firstName: "Muhammad",
    lastName: "Hamza",
    title: "Software Engineer",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Emmanuel",
    lastName: "Cruz",
    title: "Software Engineer",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Cynthia",
    lastName: "Brito-Mena",
    title: "Software Engineer",
    picture: "/teamPics/cynthia.png",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Tasnim",
    lastName: "Mollah",
    title: "Software Engineer",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Sarah",
    lastName: "Alli",
    title: "Software Engineer",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Sara",
    lastName: "Khan",
    title: "TBC",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Imran",
    lastName: "Khan",
    title: "TBC",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Matt",
    lastName: "Perez",
    title: "TBC",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Andrea",
    lastName: "Jainarine",
    title: "TBC",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
  {
    firstName: "Darwin",
    lastName: "Jean",
    title: "TBC",
    picture: "",
    summary: "",
    linkedin: "",
    github: "",
  },
];

module.exports = { aboutData };
